# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 12:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asociados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_asociado', models.IntegerField()),
                ('beneficio', models.CharField(max_length=200)),
                ('renovar_asociacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cliente', models.IntegerField()),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('dni', models.IntegerField()),
                ('direccion_de_correo', models.CharField(max_length=200)),
                ('domilicio', models.CharField(max_length=200)),
                ('telefono', models.IntegerField()),
                ('fecha_de_nacimiento', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Contrato_de_alquilacion_compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_contrato', models.IntegerField()),
                ('horario_de_alquiler_compra', models.DateTimeField(default=django.utils.timezone.now)),
                ('objetivo', models.CharField(max_length=200)),
                ('cantidad', models.IntegerField()),
                ('fecha_de_entrega', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_empleados', models.IntegerField()),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('DNI', models.IntegerField()),
                ('direccion_de_correo', models.CharField(max_length=200)),
                ('fecha_de_nacimiento', models.DateTimeField(default=django.utils.timezone.now)),
                ('numero_de_empleado', models.IntegerField()),
                ('telefono', models.CharField(max_length=200)),
                ('domicilio', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_empresas', models.IntegerField()),
                ('nombre', models.CharField(max_length=200)),
                ('direccion_de_correo', models.CharField(max_length=200)),
                ('domilicio', models.CharField(max_length=200)),
                ('telefono', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Herramientas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_de_la_herramienta', models.CharField(max_length=200)),
                ('id_herramienta', models.IntegerField()),
                ('precio', models.CharField(max_length=200)),
                ('stock', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_proveedor', models.IntegerField()),
                ('nombre_del_proveedor', models.CharField(max_length=200)),
                ('direccion_de_correo', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Turnos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_turno', models.IntegerField()),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='empresas',
            name='herramientas_que_posee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginadealquiler.Herramientas'),
        ),
        migrations.AddField(
            model_name='empleados',
            name='turnos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginadealquiler.Turnos'),
        ),
        migrations.AddField(
            model_name='contrato_de_alquilacion_compra',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginadealquiler.Empleados'),
        ),
        migrations.AddField(
            model_name='contrato_de_alquilacion_compra',
            name='herramienta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginadealquiler.Herramientas'),
        ),
        migrations.AddField(
            model_name='contrato_de_alquilacion_compra',
            name='nombre_de_la_empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginadealquiler.Empresas'),
        ),
        migrations.AddField(
            model_name='contrato_de_alquilacion_compra',
            name='nombre_del_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginadealquiler.Clientes'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='herramienta_que_posee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginadealquiler.Herramientas'),
        ),
        migrations.AddField(
            model_name='asociados',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginadealquiler.Clientes'),
        ),
        migrations.AddField(
            model_name='asociados',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginadealquiler.Empresas'),
        ),
    ]
