# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paginadealquiler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='asociados',
            name='beneficio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginadealquiler.Beneficio'),
        ),
        migrations.AlterField(
            model_name='asociados',
            name='id_asociado',
            field=models.CharField(max_length=200),
        ),
    ]
