# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 12:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginadealquiler', '0002_auto_20160926_1233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contrato_de_alquilacion_compra',
            old_name='objetivo',
            new_name='proposito',
        ),
    ]
