# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 12:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginadealquiler', '0003_auto_20160926_1239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turnos',
            old_name='nombre',
            new_name='turno',
        ),
    ]
