# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 12:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paginadealquiler', '0004_auto_20161017_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comprar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_compra', models.CharField(max_length=200)),
                ('cantidad', models.IntegerField()),
                ('total', models.IntegerField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginadealquiler.Clientes')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginadealquiler.Empleados')),
                ('herramienta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginadealquiler.Herramientas')),
            ],
        ),
    ]
