# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 11:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paginadealquiler', '0005_comprar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alquiler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_alquiler', models.CharField(max_length=200)),
                ('cantidad', models.IntegerField()),
                ('total', models.CharField(max_length=200)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginadealquiler.Clientes')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginadealquiler.Empleados')),
                ('herramienta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginadealquiler.Herramientas')),
            ],
        ),
        migrations.AlterField(
            model_name='comprar',
            name='total',
            field=models.CharField(max_length=200),
        ),
    ]
