# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 11:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('paginadealquiler', '0006_auto_20161107_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='alquiler',
            name='fecha_de_entrega',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
