from django.conf.urls import url
from . import views

urlpatterns = [
        url(r'^$', views.vistainicio),
        url(r'^herramienta/new/$', views.herramienta_new, name='herramienta_new'),
        url(r'^herramienta/edit/(?P<pk>[0-9]+)$', views.herramienta_edit, name='herramienta_edit'),
        url(r'^herramientas/', views.vistaherramientas),
        url(r'^herramienta/eliminar/(?P<pk>[0-9]+)$', views.herramienta_eliminar, name='herramienta_eliminar'),
        url(r'^clientes/', views.vistaclientes),
        url(r'^cliente/edit/(?P<pk>[0-9]+)$', views.cliente_edit, name='cliente_edit'),
        url(r'^cliente/eliminar/(?P<pk>[0-9]+)$', views.cliente_eliminar, name='cliente_eliminar'),
        url(r'^empresas/', views.vistaempresas),
        url(r'^empresa/edit/(?P<pk>[0-9]+)$', views.empresa_edit, name='empresa_edit'),
        url(r'^empresa/eliminar/(?P<pk>[0-9]+)$', views.empresa_eliminar, name='empresa_eliminar'),
        url(r'^empleados/', views.vistaempleados),
        url(r'^empleado/edit/(?P<pk>[0-9]+)$', views.empleado_edit, name='empleado_edit'),
        url(r'^empleado/eliminar/(?P<pk>[0-9]+)$', views.empleado_eliminar, name='empleado_eliminar'),
        url(r'^contrato/new/$', views.contrato_new, name='contrato_new'),
        url(r'^contrato/', views.vistacontrato),
        url(r'^contrato/edit/(?P<pk>[0-9]+)$', views.contrato_edit, name='contrato_edit'),
        url(r'^contrato/eliminar/(?P<pk>[0-9]+)$', views.contrato_eliminar, name='contrato_eliminar'),
        url(r'^proveedor/new/$', views.proveedor_new, name='proveedor_new'),
        url(r'^proveedor/', views.vistaproveedor),
        url(r'^proveedor/edit/(?P<pk>[0-9]+)$', views.proveedor_edit, name='proveedor_edit'),
        url(r'^proveedor/eliminar/(?P<pk>[0-9]+)$', views.proveedor_eliminar, name='proveedor_eliminar'),
        url(r'^asociados/', views.vistaasociados),
        url(r'^asociado/edit/(?P<pk>[0-9]+)$', views.asociado_edit, name='asociado_edit'),
        url(r'^asociado/eliminar/(?P<pk>[0-9]+)$', views.asociado_eliminar, name='asociado_eliminar'),
        url(r'^empresa/new/$', views.empresa_new, name='empresa_new'),
        url(r'^empleado/new/$', views.empleado_new, name='empleado_new'),
        url(r'^cliente/new/$', views.cliente_new, name='cliente_new'),
        url(r'^asociado/new/$', views.asociado_new, name='asociado_new'),
        url(r'^comprar/edit/(?P<pk>[0-9]+)$', views.comprar_edit, name='comprar_edit'),
        url(r'^comprar/eliminar/(?P<pk>[0-9]+)$', views.comprar_eliminar, name='comprar_eliminar'),
        url(r'^comprar/$', views.vistacomprar),
        url(r'^comprar/new/$', views.comprar_new, name='comprar_new'),
        url(r'^alquiler/$', views.vistaalquiler)
    ]
